bags:
  - 1:
    name: he.bag
    bag_path: /media/mobmi/HDD/vicon_depth_gun/ # /media/mobmi/HDD/hand_eye_calibration_datasets/
    intrinsics_path: /home/mobmi/catkin_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    target_config_path: /home/mobmi/catkin_ws/src/hand_eye_calibration/hand_eye_calibration/calib/
    cameras:
      cam_topics:
        - /camera/rgb/image_raw
      cam_intrinsics:
        - primesense_rgb_depth_gun.yaml
    target: target_large.yaml
    tf_frames:
      source:
        - depth_gun
        # - imu
      target:
        - vicon
      #  - map
